[project]
name = "Project name goes here"
version = "0.1.0"
description = "Project description goes here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.9.9",
]
