[project]
name = "dota-2-hero-picker-cv"
author = "Nader Tak"
version = "0.1.0"
description = "Dota 2 Hero Picker with Computer Vision"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
dev = [
    "pylint>=3.3.4",
    "pytest>=8.3.5",
]
