[project]
name = "dota-2-hero-picker-cv"
version = "0.1.0"
description = "Dota 2 Hero Picker with Computer Vision"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.9.9",
]
