name: Run Unit Tests

on:
  push:
    branches: ["**"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Install uv
      run: |
        python -m pip install --upgrade pip
        pip install uv

    - name: Install dependencies
      run: |
        if [ -f pyproject.toml ]; then
          uv pip install -e ".[dev]"
        else
          pip install pytest
        fi

    - name: Test with pytest
      run: |
        pytest